// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glmzrvsiwyfgyxegianf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsbXpydnNpd3lmZ3l4ZWdpYW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODIzMTAsImV4cCI6MjA2NjU1ODMxMH0.87t8Op21YGhn7Tcj_owLWRHXyrm4mwIX_7yHWj04DTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);